-module(xdb_schema_test).

%% Test Cases
-export([
  t_autogenerated_funs/1
]).

%%%===================================================================
%%% Test Cases
%%%===================================================================

-spec t_autogenerated_funs(xdb_ct:config()) -> ok.
t_autogenerated_funs(Config) ->
  Schema = xdb_lib:keyfetch(schema, Config),
  _ = Schema:primary_key(),
  lists:foreach(fun(Field) ->
    _ = maybe_apply_getter(Schema, Field),
    _ = maybe_apply_setter(Schema, Field)
  end, xdb_schema_spec:fields(Schema:schema_spec())).

%%%===================================================================
%%% Internal functions
%%%===================================================================

%% @private
maybe_apply_getter(Schema, {FieldName, _FieldType, FieldOpts}) ->
  case xdb_lib:keyfind(getter, FieldOpts) of
    false ->
      ok;
    _ ->
      apply(Schema, FieldName, [Schema:schema()])
  end.

%% @private
maybe_apply_setter(Schema, {FieldName, FieldType, FieldOpts}) ->
  case xdb_lib:keyfind(setter, FieldOpts) of
    false ->
      ok;
    _ ->
      apply(Schema, FieldName, [Schema:schema(), xdb_ct:generate_value(FieldType)])
  end.
